---
# tasks file for Dell-Networking.dellos-xstp
- name: "Provisioning xSTP configuration for dellos9"
  dellos9_config:
    src: dellos9_xstp.j2
    provider: "{{ cli }}"
  when: ansible_net_os_name == "dellos9"
#  notify: save config os9
  register: output

- name: "Provisioning xSTP configuration for dellos10"
  dellos10_config:
    src: dellos10_xstp.j2
    provider: "{{ cli }}"
  when: ansible_net_os_name == "dellos10"
#   notify: save config os10
  register: output

- name: "Provisioning xSTP configuration for dellos6"
  dellos6_config:
    src: dellos6_xstp.j2
    provider: "{{ cli }}"
  when: ansible_net_os_name == "dellos6"
#   notify: save config os6
  register: output

