---
# tasks file for dellos-xstp
- name: "Provision xSTP configuration for OS9"
  dellos9_config:
    src: dellos9_xstp.j2
    provider: "{{ cli }}"
  when: ansible_net_os_name == "dellos9"
  register: output

- name: "Provision xSTP configuration for OS10"
  dellos10_config:
    src: dellos10_xstp.j2
    provider: "{{ cli }}"
  when: ansible_net_os_name == "dellos10"
  register: output

- name: "Provision xSTP configuration for OS6"
  dellos6_config:
    src: dellos6_xstp.j2
    provider: "{{ cli }}"
  when: ansible_net_os_name == "dellos6"
  register: output

